# Generated by Django 5.1.4 on 2025-02-05 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoja_campo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meep',
            name='revisita',
        ),
        migrations.RemoveField(
            model_name='meep',
            name='visita',
        ),
    ]
