# Generated by Django 5.1.4 on 2025-02-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoja_campo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meep',
            name='revisita_fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
