# Generated by Django 5.1.4 on 2025-02-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoja_campo', '0002_meep_revisita_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='meep',
            name='revisita_usuario',
            field=models.TextField(default='', max_length=11),
        ),
    ]
