# Generated by Django 5.1.4 on 2025-02-05 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoja_campo', '0002_remove_meep_revisita_remove_meep_visita'),
    ]

    operations = [
        migrations.AddField(
            model_name='meep',
            name='revisita',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hoja_campo.ficha_tipo2'),
        ),
        migrations.AddField(
            model_name='meep',
            name='visita',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hoja_campo.ficha_tipo'),
        ),
    ]
