# Generated by Django 5.1.4 on 2025-02-05 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoja_campo', '0003_meep_revisita_meep_visita'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha_Tipo_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='meep',
            name='revisita',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hoja_campo.ficha_tipo_2'),
        ),
        
    ]
