# Generated by Django 5.1.4 on 2025-01-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, null=True)),
                ('domicilio', models.TextField(max_length=200)),
                ('ficha', models.TextField(max_length=200)),
                ('visita', models.IntegerField(choices=[(1, 'Ausente Total'), (2, 'Ausente, pero confirma domicilio'), (3, 'Vivienda desocupada'), (4, 'Rechazo'), (5, 'El domicilio No corresponde al beneficiario'), (6, 'Cambio de domicilio/Se mudaron'), (7, 'Direccion No hubicable'), (98, 'Otra causa')], default=1)),
                ('revisita', models.IntegerField(choices=[(1, 'Ausente Total'), (2, 'Ausente, pero confirma domicilio'), (3, 'Vivienda desocupada'), (4, 'Rechazo'), (5, 'El domicilio No corresponde al beneficiario'), (6, 'Cambio de domicilio/Se mudaron'), (7, 'Direccion No hubicable'), (98, 'Otra causa')], default=1)),
                ('usuario', models.TextField(max_length=100)),
                ('comentarios', models.TextField(default=0, max_length=200)),
            ],
        ),
    ]
