# Generated by Django 5.1.4 on 2025-01-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoja_campo', '0002_alter_publicacion_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='revisita',
            field=models.IntegerField(choices=[(0, 'Sin movimiento'), (1, 'Ausente Total'), (2, 'Ausente, pero confirma domicilio'), (3, 'Vivienda desocupada'), (4, 'Rechazo'), (5, 'El domicilio No corresponde al beneficiario'), (6, 'Cambio de domicilio/Se mudaron'), (7, 'Direccion No hubicable'), (9, 'Efectiva'), (98, 'Otra causa')], default=1),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='visita',
            field=models.IntegerField(choices=[(0, 'Sin movimiento'), (1, 'Ausente Total'), (2, 'Ausente, pero confirma domicilio'), (3, 'Vivienda desocupada'), (4, 'Rechazo'), (5, 'El domicilio No corresponde al beneficiario'), (6, 'Cambio de domicilio/Se mudaron'), (7, 'Direccion No hubicable'), (9, 'Efectiva'), (98, 'Otra causa')], default=1),
        ),
    ]
