# Generated by Django 5.1.4 on 2025-01-22 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoja_campo', '0005_profile_date_modified'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('domicilio', models.CharField(max_length=200)),
                ('ficha', models.TextField(max_length=12)),
                ('visita', models.IntegerField(choices=[(0, 'Sin movimiento'), (1, 'Ausente Total'), (2, 'Ausente, pero confirma domicilio'), (3, 'Vivienda desocupada'), (4, 'Rechazo'), (5, 'El domicilio No corresponde al beneficiario'), (6, 'Cambio de domicilio/Se mudaron'), (7, 'Direccion No hubicable'), (9, 'Efectiva'), (98, 'Otra causa')], default=1)),
                ('revisita', models.IntegerField(choices=[(0, 'Sin movimiento'), (1, 'Ausente Total'), (2, 'Ausente, pero confirma domicilio'), (3, 'Vivienda desocupada'), (4, 'Rechazo'), (5, 'El domicilio No corresponde al beneficiario'), (6, 'Cambio de domicilio/Se mudaron'), (7, 'Direccion No hubicable'), (9, 'Efectiva'), (98, 'Otra causa')], default=1)),
                ('comentarios', models.TextField(default=0, max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='meeps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
