# Generated by Django 5.1.4 on 2025-01-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoja_campo', '0006_meep'),
    ]

    operations = [
        migrations.AddField(
            model_name='meep',
            name='ficha_ref',
            field=models.TextField(default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='meep',
            name='ficha',
            field=models.TextField(max_length=11),
        ),
    ]
